dist: trusty

services: mongodb
language: python
python:
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install -r tests/test-requirements.txt

before_script:
  - python httpapi.py >> logs/server.log
  - sleep 5


script:
  - python tests/test_users_api.py

after_failure:
  - cat logs/server.log