dist: trusty

services: mongodb

language: python
python:
  - 3.5

install:
  - pip3 install -r requirements.txt
  - pip3 install -r tests/requirements.txt

script:
  - python3 httpapi.py
  - python3 tests/test_users_api.py
